### ISSUE TITLE
h

### ISSUE THREAD

**Issue by hpoit** [woshialex/diagnose-heart#6]

**Comment by woshialex** [comment]
I didn't quite get your question, could you be more specific?

**Comment by hpoit** [comment]
From my understanding, expectation precedes preference, both are predictors, and satisfaction is the outcome measure. I have little idea on how to build a classifier for expectation and preference.

**Comment by hpoit** [comment]
NIH: Treatment preference and patient expectation as predictors and patient satisfaction as an outcome
measure http://www.ncbi.nlm.nih.gov/pubmed/20466596

NIH: Preference associated to higher expectations http://www.ncbi.nlm.nih.gov/pubmed/25694850

Tufts, Columbia, MIT: Expectation influences preferences http://ase.tufts.edu/gdae/CS/Beer.pdf

**Comment by woshialex** [comment]
I think you question is not relevant to this code base which trains CNN models to predict the contour of the Left Ventricle based on the RMI images.

**Comment by hpoit** [comment]
Isn't the code base CNN and the application LV based on MRI, making the code base applicable to Customer Satisfaction?

I help myself in the process of explaining: okay, it can be that 1==expected, 0==not expected, but then how do you search for it in a general way? or is it only possible through a combination of many different methods?
